### ISSUE TITLE
[BUG]: Issue installing PyDgraph - Failed building wheel for grpcio

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/pydgraph#223]
### What version of pydgraph are you using?

Latest available

### What version of Python are you using?

Python 3.12.3

### Have you tried reproducing the issue with the latest release?

None

### What is the hardware spec (RAM, CPU, OS)?

Tried several models, macOS, Windows and Linux. It happen in all of them.

### What steps will reproduce the bug?

run
pip install pydgraph

### Expected behavior and actual result.

success.

### Additional information

LOGS
```

          exec(code, locals())
        File "<string>", line 537, in <module>
        File "/private/var/folders/4f/pvnf9w4515357l4s79jg_t2r0000gp/T/pip-build-env-pd0cridz/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/4f/pvnf9w4515357l4s79jg_t2r0000gp/T/pip-build-env-pd0cridz/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/4f/pvnf9w4515357l4s79jg_t2r0000gp/T/pip-build-env-pd0cridz/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/private/var/folders/4f/pvnf9w4515357l4s79jg_t2r0000gp/T/pip-build-env-pd0cridz/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/4f/pvnf9w4515357l4s79jg_t2r0000gp/T/pip-build-env-pd0cridz/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 976, in run_command
          super().run_command(command)
        File "/private/var/folders/4f/pvnf9w4515357l4s79jg_t2r0000gp/T/pip-build-env-pd0cridz/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/4f/pvnf9w4515357l4s79jg_t2r0000gp/T/pip-build-env-pd0cridz/overlay/lib/python3.12/site-packages/setuptools/command/bdist_wheel.py", line 373, in run
          self.run_command("build")
        File "/private/var/folders/4f/pvnf9w4515357l4s79jg_t2r0000gp/T/pip-build-env-pd0cridz/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/4f/pvnf9w4515357l4s79jg_t2r0000gp/T/pip-build-env-pd0cridz/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 976, in run_command
          super().run_command(command)
        File "/private/var/folders/4f/pvnf9w4515357l4s79jg_t2r0000gp/T/pip-build-env-pd0cridz/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/4f/pvnf9w4515357l4s79jg_t2r0000gp/T/pip-build-env-pd0cridz/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/private/var/folders/4f/pvnf9w4515357l4s79jg_t2r0000gp/T/pip-build-env-pd0cridz/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/4f/pvnf9w4515357l4s79jg_t2r0000gp/T/pip-build-env-pd0cridz/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 976, in run_command
          super().run_command(command)
        File "/private/var/folders/4f/pvnf9w4515357l4s79jg_t2r0000gp/T/pip-build-env-pd0cridz/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/4f/pvnf9w4515357l4s79jg_t2r0000gp/T/pip-build-env-pd0cridz/overlay/lib/python3.12/site-packages/setuptools/command/build_ext.py", line 93, in run
          _build_ext.run(self)
        File "/private/var/folders/4f/pvnf9w4515357l4s79jg_t2r0000gp/T/pip-build-env-pd0cridz/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/private/var/folders/4f/pvnf9w4515357l4s79jg_t2r0000gp/T/pip-install-rdxm110h/grpcio_2628335fefe94054992361d7163044e0/src/python/grpcio/commands.py", line 285, in build_extensions
          raise CommandError(
      commands.CommandError: Failed `build_ext` step:
      Traceback (most recent call last):
        File "/private/var/folders/4f/pvnf9w4515357l4s79jg_t2r0000gp/T/pip-build-env-pd0cridz/overlay/lib/python3.12/site-packages/setuptools/_distutils/unixccompiler.py", line 188, in _compile
          self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
        File "/private/var/folders/4f/pvnf9w4515357l4s79jg_t2r0000gp/T/pip-install-rdxm110h/grpcio_2628335fefe94054992361d7163044e0/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
          _classic_spawn(self, command)
        File "/private/var/folders/4f/pvnf9w4515357l4s79jg_t2r0000gp/T/pip-build-env-pd0cridz/overlay/lib/python3.12/site-packages/setuptools/_distutils/ccompiler.py", line 1041, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "/private/var/folders/4f/pvnf9w4515357l4s79jg_t2r0000gp/T/pip-build-env-pd0cridz/overlay/lib/python3.12/site-packages/setuptools/_distutils/spawn.py", line 68, in spawn
          raise DistutilsExecError(f"command {cmd!r} failed with exit code {exitcode}")
      distutils.errors.DistutilsExecError: command '/usr/bin/clang' failed with exit code 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/private/var/folders/4f/pvnf9w4515357l4s79jg_t2r0000gp/T/pip-install-rdxm110h/grpcio_2628335fefe94054992361d7163044e0/src/python/grpcio/commands.py", line 281, in build_extensions
          build_ext.build_ext.build_extensions(self)
        File "/private/var/folders/4f/pvnf9w4515357l4s79jg_t2r0000gp/T/pip-build-env-pd0cridz/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
          self._build_extensions_serial()
        File "/private/var/folders/4f/pvnf9w4515357l4s79jg_t2r0000gp/T/pip-build-env-pd0cridz/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
          self.build_extension(ext)
        File "/private/var/folders/4f/pvnf9w4515357l4s79jg_t2r0000gp/T/pip-build-env-pd0cridz/overlay/lib/python3.12/site-packages/setuptools/command/build_ext.py", line 254, in build_extension
          _build_ext.build_extension(self, ext)
        File "/private/var/folders/4f/pvnf9w4515357l4s79jg_t2r0000gp/T/pip-build-env-pd0cridz/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
          objects = self.compiler.compile(
                    ^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/4f/pvnf9w4515357l4s79jg_t2r0000gp/T/pip-install-rdxm110h/grpcio_2628335fefe94054992361d7163044e0/src/python/grpcio/_parallel_compile_patch.py", line 58, in _parallel_compile
          multiprocessing.pool.ThreadPool(BUILD_EXT_COMPILER_JOBS).map(
        File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/pool.py", line 367, in map
          return self._map_async(func, iterable, mapstar, chunksize).get()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/pool.py", line 774, in get
          raise self._value
        File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/pool.py", line 125, in worker
          result = (True, func(*args, **kwds))
                          ^^^^^^^^^^^^^^^^^^^
        File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/pool.py", line 48, in mapstar
          return list(map(*args))
                 ^^^^^^^^^^^^^^^^
        File "/private/var/folders/4f/pvnf9w4515357l4s79jg_t2r0000gp/T/pip-install-rdxm110h/grpcio_2628335fefe94054992361d7163044e0/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/private/var/folders/4f/pvnf9w4515357l4s79jg_t2r0000gp/T/pip-install-rdxm110h/grpcio_2628335fefe94054992361d7163044e0/src/python/grpcio/commands.py", line 264, in new_compile
          return old_compile(obj, src, ext, cc_args, extra_postargs,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/4f/pvnf9w4515357l4s79jg_t2r0000gp/T/pip-build-env-pd0cridz/overlay/lib/python3.12/site-packages/setuptools/_distutils/unixccompiler.py", line 190, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command '/usr/bin/clang' failed with exit code 1
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for grpcio
Failed to build grpcio
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (grpcio)
```

**Comment by weasdown** [comment]
I've had this problem too with Python 3.12.4 and pydgraph 23.0.2 on Windows 11 and 10. The only way I could get pydgraph to install was to use Python 3.11 (3.11.9 specifically). End of my error text with Python 3.12:
```
      distutils.errors.CompileError: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX86\\x64\\cl.exe' failed with exit code 1

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for grpcio
Failed to build grpcio
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (grpcio)
```

**Comment by weasdown** [comment]
Installing worked for me today in a venv with Python 3.12:

```shell
> python -m pip install pydgraph
Collecting pydgraph
  Downloading pydgraph-24.0.2-py3-none-any.whl.metadata (29 kB)
Collecting grpcio<2.0.0,>=1.54.3 (from pydgraph)
  Downloading grpcio-1.68.0-cp312-cp312-win_amd64.whl.metadata (4.0 kB)
Collecting protobuf<6.0.0,>=4.22.3 (from pydgraph)
  Downloading protobuf-5.28.3-cp310-abi3-win_amd64.whl.metadata (592 bytes)
Downloading pydgraph-24.0.2-py3-none-any.whl (29 kB)
Downloading grpcio-1.68.0-cp312-cp312-win_amd64.whl (4.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 56.2 MB/s eta 0:00:00
Downloading protobuf-5.28.3-cp310-abi3-win_amd64.whl (431 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 431.5/431.5 kB ? eta 0:00:00
Installing collected packages: protobuf, grpcio, pydgraph
Successfully installed grpcio-1.68.0 protobuf-5.28.3 pydgraph-24.0.2
```
